[package]
name = "extrack"
version = "0.1.0"
edition = "2021"

[lib]
name = "extrack"
path = "src/lib.rs"

[[bin]]
name = "extrack-bin"
path = "src/main.rs"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.27", features = ["derive"] }
